/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3a6a0044-da5e-48a8-b1fd-581be54060e6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eszK9YDaj",
    "aws_user_pools_web_client_id": "2aavhm05n8f740lkol772pvtgu",
    "oauth": {}
};


export default awsmobile;
